include: package:lints/recommended.yaml
analyzer:
  language:
    strict-casts: true
  errors:
    unused_import: error
    unused_local_variable: error
    dead_code: error

linter:
  rules:
    - always_declare_return_types
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - comment_references
    - directives_ordering
    - no_adjacent_strings_in_list
    - omit_local_variable_types
    - only_throw_errors
    - package_api_docs
    - prefer_const_constructors
    - prefer_single_quotes
    - sort_child_properties_last
    - test_types_in_equals
    - throw_in_finally
    - unawaited_futures
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_statements
