# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
targets:
  $default:
    builders:
      build_version:
        enabled: true
      pana:
        generate_for:
          include:
          - pubspec.yaml
          - lib/src/model.dart
          - lib/src/version.dart
      json_serializable:
        # tool/builder.dart handles this
        enabled: false

builders:
  pana:
    import: tool/builder.dart
    builder_factories: ["buildPana"]
    build_extensions: {".dart": [".g.dart"]}
    build_to: source
