# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
targets:
  $default:
    builders:
      pana|version:
        enabled: true
      pana:
        generate_for:
          include:
          - lib/src/model.dart
          - lib/src/version.dart
      json_serializable:
        # tool/builder.dart handles this
        enabled: false

builders:
  pana:
    # See https://github.com/dart-lang/build/issues/1423
    import: "../../../tool/builder.dart"
    builder_factories: ["buildPana"]
    build_extensions: {".dart": [".g.dart"]}
    build_to: source

  version:
    # See https://github.com/dart-lang/build/issues/1423
    import: "../../../tool/builder.dart"
    builder_factories: ["versionBuilder"]
    build_extensions: {"$lib$": ["src/version.dart"]}
    build_to: source
