# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
# Do not use `pub run build_runner` on the package - use `dart tool/build.dart` instead!
targets:
  pana:
    sources:
      - 'pubspec.yaml'
      - 'lib/**'
      - 'tool/**'
