# A CI configuration to write comments on PRs.

name: Comment on the pull request

permissions:
  contents: read

on:
  # Trigger this workflow after the Publish workflow completes. This workflow will have permissions to
  # do things like create comments on the PR, even if the original workflow couldn't.
  workflow_run: # zizmor: ignore[dangerous-triggers]
    workflows:
      - Publish
    types:
      - completed

jobs:
  upload:
    uses: dart-lang/ecosystem/.github/workflows/post_summaries.yaml@1bdafd85bb97b331ddd683577f48a5dfa7f4cb49 # main
    permissions:
      pull-requests: write
